# Generated by Django 5.0.5 on 2024-05-11 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_grade_date_remove_grade_max_value_and_more'),
        ('core', '0004_student_student_number_sections_student_student_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField()),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
