# Generated by Django 5.0.5 on 2024-05-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='SchoolAdmin',
            new_name='schoolAdmin',
        ),
    ]
