# Generated by Django 5.0.5 on 2024-05-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='city',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='country',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='state',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='school',
        ),
    ]
