# Generated by Django 5.0.5 on 2024-05-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_rename_city_school_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='school',
        ),
    ]
