# Generated by Django 5.0.5 on 2024-05-11 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_subject_code_alter_subject_name_note_and_more'),
        ('schools', '0003_remove_classroom_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='school',
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.school'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subjects',
            field=models.ManyToManyField(related_name='grades', to='academics.subject'),
        ),
    ]
