# Generated by Django 5.0.5 on 2024-05-12 18:15

import django.db.models.deletion
import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_remove_section_school_grade_school_grade_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='Region',
            new_name='region',
        ),
        migrations.AlterField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=schools.models.school_logo_path),
        ),
    ]
