# Generated by Django 5.0.5 on 2024-05-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_rename_region_school_region_alter_grade_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sigle',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
