# Generated by Django 5.0.5 on 2024-05-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_sigle_section_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slogan',
            field=models.CharField(default='NC', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='sigle',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
