# Generated by Django 5.0.5 on 2024-05-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_subject_code_alter_subject_name_note_and_more'),
        ('schools', '0007_school_slogan_alter_school_sigle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='grades', to='academics.subject'),
        ),
    ]
