# Generated by Django 5.0.5 on 2024-06-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='father_first_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='father_job',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='father_last_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_first_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_job',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_last_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='tutor_first_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='tutor_job',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='tutor_last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_sex',
            field=models.CharField(choices=[('male', 'garçon'), ('female', 'fille')], default='NC', max_length=20),
        ),
    ]
