# Generated by Django 5.0.5 on 2024-06-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('core', '0003_remove_student_student_id_user_student_id'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_schools',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='schools.section'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='academics.subject'),
        ),
    ]
