# Generated by Django 5.0.5 on 2024-05-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number_sections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_sex',
            field=models.CharField(choices=[('male', 'garçon'), ('female', 'fille')], default='NC', max_length=20, null=True),
        ),
    ]
