# Generated by Django 5.0.5 on 2024-05-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_student_number_sections_student_student_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladmin',
            name='role',
            field=models.CharField(choices=[('school_admin', "Administrateur d'école"), ('content_integrator', 'Intégrateur de contenu'), ('moderator', 'Modérateur'), ('staff', 'Personnel'), ('proviseur ', 'Proviseur '), ('censeur ', 'Censeur '), ('adjoint', 'Adjoint au proviseur'), ('chef_de_travaux', 'Chef de travaux'), ('Responsable_d_équipe_pédagogique ', "Responsable d'équipe pédagogique "), ('directeur ', 'Directeur ')], max_length=50),
        ),
    ]
