# Generated by Django 5.0.5 on 2024-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_teacher_teacher_schools_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_children_schools',
            field=models.ManyToManyField(blank=True, null=True, related_name='parents', to='schools.school'),
        ),
    ]
