# Generated by Django 5.0.5 on 2024-05-12 15:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_schooladmin_role_alter_user_is_active'),
        ('schools', '0004_remove_section_school_grade_school_grade_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_schools',
            field=models.ManyToManyField(related_name='teachers', to='schools.section'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_picture_path),
        ),
    ]
